# Generated by Django 3.2.13 on 2022-10-15 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('component', models.CharField(max_length=120)),
                ('path', models.CharField(max_length=120)),
                ('hidden', models.BooleanField(default=False)),
                ('subCount', models.IntegerField()),
                ('menuSort', models.IntegerField()),
                ('parentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=120)),
                ('menu', models.ManyToManyField(to='system.Menu')),
            ],
        ),
    ]
