# Generated by Django 3.2.13 on 2022-10-15 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='InputFiles')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.process')),
            ],
        ),
    ]
