# Generated by Django 3.2.10 on 2022-05-21 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Process',
        ),
    ]
